#ifndef WAYPOINTPLANMANAGERSERVICE_THR_IMPL_MCMP_PROC_SW_WPM_WAYPOINTPLANMANAGERSERVICE_H
#define WAYPOINTPLANMANAGERSERVICE_THR_IMPL_MCMP_PROC_SW_WPM_WAYPOINTPLANMANAGERSERVICE_H

#include <all.h>

Unit hamr_SW_WaypointPlanManagerService_thr_Impl_MCMP_PROC_SW_WPM_WaypointPlanManagerService_initialise_(STACK_FRAME_ONLY);

Unit hamr_SW_WaypointPlanManagerService_thr_Impl_MCMP_PROC_SW_WPM_WaypointPlanManagerService_finalise_(STACK_FRAME_ONLY);

Unit hamr_SW_WaypointPlanManagerService_thr_Impl_MCMP_PROC_SW_WPM_WaypointPlanManagerService_timeTriggered_(STACK_FRAME_ONLY);

#endif
