#ifndef RADIODRIVER_THR_IMPL_RADIO_RADIODRIVER_ADAPTER_H
#define RADIODRIVER_THR_IMPL_RADIO_RADIODRIVER_ADAPTER_H

#include <all.h>

Unit attestation_gate_RadioDriver_RadioDriver_thr_Impl_radio_RadioDriver_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit attestation_gate_RadioDriver_RadioDriver_thr_Impl_radio_RadioDriver_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit attestation_gate_RadioDriver_RadioDriver_thr_Impl_radio_RadioDriver_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints attestation_gate_RadioDriver_RadioDriver_thr_Impl_radio_RadioDriver_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
