#ifndef GEOFENCEMONITOR_IMPL_SW_GEOFENCEMONITOR_GEOFENCEMONITOR_H
#define GEOFENCEMONITOR_IMPL_SW_GEOFENCEMONITOR_GEOFENCEMONITOR_H

#include <all.h>

Unit HAMR_SW_GeofenceMonitor_Impl_SW_GeofenceMonitor_GeofenceMonitor_initialise_(STACK_FRAME_ONLY);

Unit HAMR_SW_GeofenceMonitor_Impl_SW_GeofenceMonitor_GeofenceMonitor_finalise_(STACK_FRAME_ONLY);

Unit HAMR_SW_GeofenceMonitor_Impl_SW_GeofenceMonitor_GeofenceMonitor_handle_FlightPlan_In_(
  STACK_FRAME
  HAMR_SW_Mission value);

#endif
