#ifndef GEOFENCEMONITOR_IMPL_SW_GEOFENCEMONITOR_GEOFENCEMONITOR_ADAPTER_H
#define GEOFENCEMONITOR_IMPL_SW_GEOFENCEMONITOR_GEOFENCEMONITOR_ADAPTER_H

#include <all.h>

Unit HAMR_SW_GeofenceMonitor_Impl_SW_GeofenceMonitor_GeofenceMonitor_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit HAMR_SW_GeofenceMonitor_Impl_SW_GeofenceMonitor_GeofenceMonitor_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit HAMR_SW_GeofenceMonitor_Impl_SW_GeofenceMonitor_GeofenceMonitor_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints HAMR_SW_GeofenceMonitor_Impl_SW_GeofenceMonitor_GeofenceMonitor_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
