#include <WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter.h>

Unit HAMR_SW_WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter.c", "", "HAMR_SW_WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter_initialiseArchitecture", 0);

  HAMR_WaypointManager_Impl_SW_WaypointManager_WaypointManager_WaypointManager_initialiseArchitecture(SF_LAST);
}

Unit HAMR_SW_WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter.c", "", "HAMR_SW_WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter_initialiseEntryPoint", 0);

  HAMR_WaypointManager_Impl_SW_WaypointManager_WaypointManager_WaypointManager_initialiseEntryPoint(SF_LAST);
}

Unit HAMR_SW_WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter.c", "", "HAMR_SW_WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter_computeEntryPoint", 0);

  HAMR_WaypointManager_Impl_SW_WaypointManager_WaypointManager_WaypointManager_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints HAMR_SW_WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter.c", "", "HAMR_SW_WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter_entryPoints", 0);

  return HAMR_WaypointManager_Impl_SW_WaypointManager_WaypointManager_WaypointManager_entryPoints(SF_LAST);
}
