#ifndef WAYPOINTMANAGER_IMPL_SW_WAYPOINTMANAGER_WAYPOINTMANAGER_ADAPTER_H
#define WAYPOINTMANAGER_IMPL_SW_WAYPOINTMANAGER_WAYPOINTMANAGER_ADAPTER_H

#include <all.h>

Unit HAMR_SW_WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit HAMR_SW_WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit HAMR_SW_WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints HAMR_SW_WaypointManager_Impl_SW_WaypointManager_WaypointManager_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
