#ifndef INPUT_IMPL_INPUT_INPUT_ADAPTER_H
#define INPUT_IMPL_INPUT_INPUT_ADAPTER_H

#include <all.h>

Unit CASE_MONITOR_2_TEST_VPM_TEST_Input_impl_Input_Input_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit CASE_MONITOR_2_TEST_VPM_TEST_Input_impl_Input_Input_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit CASE_MONITOR_2_TEST_VPM_TEST_Input_impl_Input_Input_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints CASE_MONITOR_2_TEST_VPM_TEST_Input_impl_Input_Input_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
