#ifndef CASE_ATTESTATIONGATE_IMPL_SW_ATTESTATIONGATE_CASE_ATTESTATIONGATE_H
#define CASE_ATTESTATIONGATE_IMPL_SW_ATTESTATIONGATE_CASE_ATTESTATIONGATE_H

#include <all.h>

Unit HAMR_SW_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_initialise_(STACK_FRAME_ONLY);

Unit HAMR_SW_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_finalise_(STACK_FRAME_ONLY);

Unit HAMR_SW_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_handle_MissionCommand_in_(
  STACK_FRAME
  HAMR_SW_RF_Msg_Impl value);

Unit HAMR_SW_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_handle_TrustedIds_(
  STACK_FRAME
  HAMR_SW_Address_Impl value);

#endif
