#ifndef CASE_ATTESTATIONMANAGER_IMPL_SW_ATTESTATIONMANAGER_CASE_ATTESTATIONMANAGER_H
#define CASE_ATTESTATIONMANAGER_IMPL_SW_ATTESTATIONMANAGER_CASE_ATTESTATIONMANAGER_H

#include <all.h>

Unit HAMR_SW_CASE_AttestationManager_Impl_SW_AttestationManager_CASE_AttestationManager_initialise_(STACK_FRAME_ONLY);

Unit HAMR_SW_CASE_AttestationManager_Impl_SW_AttestationManager_CASE_AttestationManager_finalise_(STACK_FRAME_ONLY);

Unit HAMR_SW_CASE_AttestationManager_Impl_SW_AttestationManager_CASE_AttestationManager_handle_AttestationResponse_(
  STACK_FRAME
  HAMR_CASE_Model_Transformations_CASE_AttestationResponseMsg_Impl value);

#endif
