#ifndef CASE_ATTESTATIONMANAGER_IMPL_SW_ATTESTATIONMANAGER_CASE_ATTESTATIONMANAGER_API_H
#define CASE_ATTESTATIONMANAGER_IMPL_SW_ATTESTATIONMANAGER_CASE_ATTESTATIONMANAGER_API_H

#include <all.h>

// This file was auto-generated.  Do not edit

void api_put_AttestationRequest__HAMR_SW_CASE_AttestationManager_Impl_SW_AttestationManager_CASE_AttestationManager(
  STACK_FRAME
  HAMR_CASE_Model_Transformations_CASE_AttestationRequestMsg_Impl value);

bool api_get_AttestationResponse__HAMR_SW_CASE_AttestationManager_Impl_SW_AttestationManager_CASE_AttestationManager(
  STACK_FRAME
  HAMR_CASE_Model_Transformations_CASE_AttestationResponseMsg_Impl value);

void api_put_TrustedIds__HAMR_SW_CASE_AttestationManager_Impl_SW_AttestationManager_CASE_AttestationManager(
  STACK_FRAME
  HAMR_SW_Address_Impl value);

void api_logInfo__HAMR_SW_CASE_AttestationManager_Impl_SW_AttestationManager_CASE_AttestationManager(
  STACK_FRAME
  String str);

void api_logDebug__HAMR_SW_CASE_AttestationManager_Impl_SW_AttestationManager_CASE_AttestationManager(
  STACK_FRAME
  String str);

void api_logError__HAMR_SW_CASE_AttestationManager_Impl_SW_AttestationManager_CASE_AttestationManager(
  STACK_FRAME
  String str);

#endif
