#ifndef FILTER_T_FILTER_FILTER_ADAPTER_H
#define FILTER_T_FILTER_FILTER_ADAPTER_H

#include <all.h>

Unit pfc_PFC_filter_t_filter_filter_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit pfc_PFC_filter_t_filter_filter_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit pfc_PFC_filter_t_filter_filter_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints pfc_PFC_filter_t_filter_filter_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
