#ifndef ATTESTATIONMANAGER_IMPL_SW_ATTESTATIONMANAGER_ATTESTATIONMANAGER_H
#define ATTESTATIONMANAGER_IMPL_SW_ATTESTATIONMANAGER_ATTESTATIONMANAGER_H

#include <all.h>

Unit HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_initialise_(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_finalise_(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_timeTriggered_(STACK_FRAME_ONLY);

#endif
