#ifndef INPUT_IMPL_INPUT_INPUT_H
#define INPUT_IMPL_INPUT_INPUT_H

#include <all.h>

Unit CASE_MONITOR_2_TEST_VPM_TEST_Input_impl_Input_Input_initialise_(STACK_FRAME_ONLY);

Unit CASE_MONITOR_2_TEST_VPM_TEST_Input_impl_Input_Input_finalise_(STACK_FRAME_ONLY);

Unit CASE_MONITOR_2_TEST_VPM_TEST_Input_impl_Input_Input_timeTriggered_(STACK_FRAME_ONLY);

#endif
