#include <CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter.h>

Unit CASE_MONITOR_2_TEST_VPM_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter.c", "", "CASE_MONITOR_2_TEST_VPM_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter_initialiseArchitecture", 0);

  CASE_MONITOR_2_TEST_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_CASE_Monitor_initialiseArchitecture(SF_LAST);
}

Unit CASE_MONITOR_2_TEST_VPM_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter.c", "", "CASE_MONITOR_2_TEST_VPM_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter_initialiseEntryPoint", 0);

  CASE_MONITOR_2_TEST_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_CASE_Monitor_initialiseEntryPoint(SF_LAST);
}

Unit CASE_MONITOR_2_TEST_VPM_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter.c", "", "CASE_MONITOR_2_TEST_VPM_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter_computeEntryPoint", 0);

  CASE_MONITOR_2_TEST_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_CASE_Monitor_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints CASE_MONITOR_2_TEST_VPM_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter.c", "", "CASE_MONITOR_2_TEST_VPM_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter_entryPoints", 0);

  return CASE_MONITOR_2_TEST_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_CASE_Monitor_entryPoints(SF_LAST);
}
