#ifndef CASE_MONITOR1_IMPL_CASE_MONITOR_CASE_MONITOR_ADAPTER_H
#define CASE_MONITOR1_IMPL_CASE_MONITOR_CASE_MONITOR_ADAPTER_H

#include <all.h>

Unit CASE_MONITOR_2_TEST_VPM_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit CASE_MONITOR_2_TEST_VPM_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit CASE_MONITOR_2_TEST_VPM_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints CASE_MONITOR_2_TEST_VPM_CASE_Monitor1_Impl_CASE_Monitor_CASE_Monitor_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
