#ifndef RADIODRIVER_IMPL_SW_RADIO_RADIODRIVER_ADAPTER_H
#define RADIODRIVER_IMPL_SW_RADIO_RADIODRIVER_ADAPTER_H

#include <all.h>

Unit HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_RadioDriver_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_RadioDriver_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_RadioDriver_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_RadioDriver_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
