#ifndef UARTDRIVER_IMPL_SW_UART_UARTDRIVER_ADAPTER_H
#define UARTDRIVER_IMPL_SW_UART_UARTDRIVER_ADAPTER_H

#include <all.h>

Unit HAMR_SW_UARTDriver_Impl_SW_UART_UARTDriver_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit HAMR_SW_UARTDriver_Impl_SW_UART_UARTDriver_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit HAMR_SW_UARTDriver_Impl_SW_UART_UARTDriver_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints HAMR_SW_UARTDriver_Impl_SW_UART_UARTDriver_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
