#ifndef RADIODRIVER_ATTESTATION_IMPL_SW_RADIO_RADIODRIVER_ATTESTATION_ADAPTER_H
#define RADIODRIVER_ATTESTATION_IMPL_SW_RADIO_RADIODRIVER_ATTESTATION_ADAPTER_H

#include <all.h>

Unit HAMR_SW_RadioDriver_Attestation_Impl_SW_Radio_RadioDriver_Attestation_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit HAMR_SW_RadioDriver_Attestation_Impl_SW_Radio_RadioDriver_Attestation_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit HAMR_SW_RadioDriver_Attestation_Impl_SW_Radio_RadioDriver_Attestation_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints HAMR_SW_RadioDriver_Attestation_Impl_SW_Radio_RadioDriver_Attestation_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
