#ifndef FLYZONEDATABASE_IMPL_SW_FLYZONES_FLYZONEDATABASE_ADAPTER_H
#define FLYZONEDATABASE_IMPL_SW_FLYZONES_FLYZONEDATABASE_ADAPTER_H

#include <all.h>

Unit HAMR_SW_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit HAMR_SW_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit HAMR_SW_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints HAMR_SW_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
