#include <FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter.h>

Unit HAMR_SW_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter.c", "", "HAMR_SW_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter_initialiseArchitecture", 0);

  HAMR_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_FlyZoneDatabase_initialiseArchitecture(SF_LAST);
}

Unit HAMR_SW_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter.c", "", "HAMR_SW_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter_initialiseEntryPoint", 0);

  HAMR_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_FlyZoneDatabase_initialiseEntryPoint(SF_LAST);
}

Unit HAMR_SW_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter.c", "", "HAMR_SW_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter_computeEntryPoint", 0);

  HAMR_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_FlyZoneDatabase_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints HAMR_SW_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter.c", "", "HAMR_SW_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_adapter_entryPoints", 0);

  return HAMR_FlyZoneDatabase_Impl_SW_FlyZones_FlyZoneDatabase_FlyZoneDatabase_entryPoints(SF_LAST);
}
