#ifndef FLIGHTCONTROLLER_IMPL_SW_FLIGHTCONTROLLER_FLIGHTCONTROLLER_H
#define FLIGHTCONTROLLER_IMPL_SW_FLIGHTCONTROLLER_FLIGHTCONTROLLER_H

#include <all.h>

Unit HAMR_SW_FlightController_Impl_SW_FlightController_FlightController_initialise_(STACK_FRAME_ONLY);

Unit HAMR_SW_FlightController_Impl_SW_FlightController_FlightController_finalise_(STACK_FRAME_ONLY);

Unit HAMR_SW_FlightController_Impl_SW_FlightController_FlightController_timeTriggered_(STACK_FRAME_ONLY);

#endif
