#include <RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter.h>

Unit HAMR_SW_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter.c", "", "HAMR_SW_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter_initialiseArchitecture", 0);

  HAMR_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_RadioDriver_Attestation_initialiseArchitecture(SF_LAST);
}

Unit HAMR_SW_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter.c", "", "HAMR_SW_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter_initialiseEntryPoint", 0);

  HAMR_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_RadioDriver_Attestation_initialiseEntryPoint(SF_LAST);
}

Unit HAMR_SW_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter.c", "", "HAMR_SW_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter_computeEntryPoint", 0);

  HAMR_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_RadioDriver_Attestation_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints HAMR_SW_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter.c", "", "HAMR_SW_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_adapter_entryPoints", 0);

  return HAMR_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_RadioDriver_Attestation_entryPoints(SF_LAST);
}
