#ifndef CONSUMER_T_I_CONSUMER_CONSUMER_ADAPTER_H
#define CONSUMER_T_I_CONSUMER_CONSUMER_ADAPTER_H

#include <all.h>

Unit base_test_event_port_periodic_domains_consumer_t_i_consumer_consumer_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit base_test_event_port_periodic_domains_consumer_t_i_consumer_consumer_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit base_test_event_port_periodic_domains_consumer_t_i_consumer_consumer_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints base_test_event_port_periodic_domains_consumer_t_i_consumer_consumer_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
