#ifndef PRODUCER_T_I_PRODUCER_PRODUCER_ADAPTER_H
#define PRODUCER_T_I_PRODUCER_PRODUCER_ADAPTER_H

#include <all.h>

Unit base_test_event_port_periodic_domains_producer_t_i_producer_producer_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit base_test_event_port_periodic_domains_producer_t_i_producer_producer_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit base_test_event_port_periodic_domains_producer_t_i_producer_producer_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints base_test_event_port_periodic_domains_producer_t_i_producer_producer_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
