#include <AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter.h>

Unit HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter.c", "", "HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter_initialiseArchitecture", 0);

  HAMR_AttestationManager_Impl_SW_AttestationManager_AttestationManager_AttestationManager_initialiseArchitecture(SF_LAST);
}

Unit HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter.c", "", "HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter_initialiseEntryPoint", 0);

  HAMR_AttestationManager_Impl_SW_AttestationManager_AttestationManager_AttestationManager_initialiseEntryPoint(SF_LAST);
}

Unit HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter.c", "", "HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter_computeEntryPoint", 0);

  HAMR_AttestationManager_Impl_SW_AttestationManager_AttestationManager_AttestationManager_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter.c", "", "HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter_entryPoints", 0);

  return HAMR_AttestationManager_Impl_SW_AttestationManager_AttestationManager_AttestationManager_entryPoints(SF_LAST);
}
