#ifndef RADIODRIVER_IMPL_SW_RADIO_RADIODRIVER_H
#define RADIODRIVER_IMPL_SW_RADIO_RADIODRIVER_H

#include <all.h>

Unit HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_RadioDriver_initialise_(STACK_FRAME_ONLY);

Unit HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_RadioDriver_finalise_(STACK_FRAME_ONLY);

Unit HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_RadioDriver_handle_AttestationTesterResponse_(
  STACK_FRAME
  IS_C4F575 value);

#endif
