#include <all.h>

B Type__eq(void *t1, void *t2) {
  TYPE type = ((Type) t1)->type;
  if (type != ((Type) t2)->type) return F;
  switch (type) {
    case TTuple2_EC3B57: return Tuple2_EC3B57__eq((Tuple2_EC3B57) t1, (Tuple2_EC3B57) t2);
    case THAMR_Simple_V4_Base_Types_Bits_Payload: return HAMR_Simple_V4_Base_Types_Bits_Payload__eq((HAMR_Simple_V4_Base_Types_Bits_Payload) t1, (HAMR_Simple_V4_Base_Types_Bits_Payload) t2);
    case THAMR_Simple_V4_SW_AttestationTester_Impl_Initialization_Api: return HAMR_Simple_V4_SW_AttestationTester_Impl_Initialization_Api__eq((HAMR_Simple_V4_SW_AttestationTester_Impl_Initialization_Api) t1, (HAMR_Simple_V4_SW_AttestationTester_Impl_Initialization_Api) t2);
    case THAMR_Simple_V4_SW_AttestationTester_Impl_Operational_Api: return HAMR_Simple_V4_SW_AttestationTester_Impl_Operational_Api__eq((HAMR_Simple_V4_SW_AttestationTester_Impl_Operational_Api) t1, (HAMR_Simple_V4_SW_AttestationTester_Impl_Operational_Api) t2);
    case THAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge: return HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge__eq((HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge) t1, (HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge) t2);
    case THAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge_EntryPoints: return HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge_EntryPoints__eq((HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge_EntryPoints) t1, (HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge_EntryPoints) t2);
    case THAMR_Simple_V4_SW_FlightController_Impl_Initialization_Api: return HAMR_Simple_V4_SW_FlightController_Impl_Initialization_Api__eq((HAMR_Simple_V4_SW_FlightController_Impl_Initialization_Api) t1, (HAMR_Simple_V4_SW_FlightController_Impl_Initialization_Api) t2);
    case THAMR_Simple_V4_SW_FlightController_Impl_Operational_Api: return HAMR_Simple_V4_SW_FlightController_Impl_Operational_Api__eq((HAMR_Simple_V4_SW_FlightController_Impl_Operational_Api) t1, (HAMR_Simple_V4_SW_FlightController_Impl_Operational_Api) t2);
    case THAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge: return HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge__eq((HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge) t1, (HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge) t2);
    case THAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge_EntryPoints: return HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge_EntryPoints__eq((HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge_EntryPoints) t1, (HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge_EntryPoints) t2);
    case THAMR_Simple_V4_SW_FlightPlanner_Impl_Initialization_Api: return HAMR_Simple_V4_SW_FlightPlanner_Impl_Initialization_Api__eq((HAMR_Simple_V4_SW_FlightPlanner_Impl_Initialization_Api) t1, (HAMR_Simple_V4_SW_FlightPlanner_Impl_Initialization_Api) t2);
    case THAMR_Simple_V4_SW_FlightPlanner_Impl_Operational_Api: return HAMR_Simple_V4_SW_FlightPlanner_Impl_Operational_Api__eq((HAMR_Simple_V4_SW_FlightPlanner_Impl_Operational_Api) t1, (HAMR_Simple_V4_SW_FlightPlanner_Impl_Operational_Api) t2);
    case THAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge: return HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge__eq((HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge) t1, (HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge) t2);
    case THAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge_EntryPoints: return HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge_EntryPoints__eq((HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge_EntryPoints) t1, (HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge_EntryPoints) t2);
    case THAMR_Simple_V4_SW_RadioDriver_Impl_Initialization_Api: return HAMR_Simple_V4_SW_RadioDriver_Impl_Initialization_Api__eq((HAMR_Simple_V4_SW_RadioDriver_Impl_Initialization_Api) t1, (HAMR_Simple_V4_SW_RadioDriver_Impl_Initialization_Api) t2);
    case THAMR_Simple_V4_SW_RadioDriver_Impl_Operational_Api: return HAMR_Simple_V4_SW_RadioDriver_Impl_Operational_Api__eq((HAMR_Simple_V4_SW_RadioDriver_Impl_Operational_Api) t1, (HAMR_Simple_V4_SW_RadioDriver_Impl_Operational_Api) t2);
    case THAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge: return HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge__eq((HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge) t1, (HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge) t2);
    case THAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge_EntryPoints: return HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge_EntryPoints__eq((HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge_EntryPoints) t1, (HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge_EntryPoints) t2);
    case TIS_AA0F82: return IS_AA0F82__eq((IS_AA0F82) t1, (IS_AA0F82) t2);
    case TIS_C4F575: return IS_C4F575__eq((IS_C4F575) t1, (IS_C4F575) t2);
    case TIS_948B60: return IS_948B60__eq((IS_948B60) t1, (IS_948B60) t2);
    case TIS_82ABD8: return IS_82ABD8__eq((IS_82ABD8) t1, (IS_82ABD8) t2);
    case TIS_7E8796: return IS_7E8796__eq((IS_7E8796) t1, (IS_7E8796) t2);
    case TIS_08117A: return IS_08117A__eq((IS_08117A) t1, (IS_08117A) t2);
    case TIS_820232: return IS_820232__eq((IS_820232) t1, (IS_820232) t2);
    case TMBox2_1029D1: return MBox2_1029D1__eq((MBox2_1029D1) t1, (MBox2_1029D1) t2);
    case TMBox2_1CBFC4: return MBox2_1CBFC4__eq((MBox2_1CBFC4) t1, (MBox2_1CBFC4) t2);
    case TMS_B5E3E6: return MS_B5E3E6__eq((MS_B5E3E6) t1, (MS_B5E3E6) t2);
    case TMS_E444B2: return MS_E444B2__eq((MS_E444B2) t1, (MS_E444B2) t2);
    case TMS_83D5EB: return MS_83D5EB__eq((MS_83D5EB) t1, (MS_83D5EB) t2);
    case TMS_2590FE: return MS_2590FE__eq((MS_2590FE) t1, (MS_2590FE) t2);
    case TMS_F55A18: return MS_F55A18__eq((MS_F55A18) t1, (MS_F55A18) t2);
    case TMS_30A5B4: return MS_30A5B4__eq((MS_30A5B4) t1, (MS_30A5B4) t2);
    case TNone_600AAD: return None_600AAD__eq((None_600AAD) t1, (None_600AAD) t2);
    case TNone_6557E1: return None_6557E1__eq((None_6557E1) t1, (None_6557E1) t2);
    case TNone_4E54E3: return None_4E54E3__eq((None_4E54E3) t1, (None_4E54E3) t2);
    case TNone_2849BF: return None_2849BF__eq((None_2849BF) t1, (None_2849BF) t2);
    case TNone_43D596: return None_43D596__eq((None_43D596) t1, (None_43D596) t2);
    case TNone_E951B6: return None_E951B6__eq((None_E951B6) t1, (None_E951B6) t2);
    case TNone_3F37D3: return None_3F37D3__eq((None_3F37D3) t1, (None_3F37D3) t2);
    case TNone_C64652: return None_C64652__eq((None_C64652) t1, (None_C64652) t2);
    case TNone_3026C5: return None_3026C5__eq((None_3026C5) t1, (None_3026C5) t2);
    case TNone_5C1355: return None_5C1355__eq((None_5C1355) t1, (None_5C1355) t2);
    case TNone_76463B: return None_76463B__eq((None_76463B) t1, (None_76463B) t2);
    case TNone_734370: return None_734370__eq((None_734370) t1, (None_734370) t2);
    case TNone_964667: return None_964667__eq((None_964667) t1, (None_964667) t2);
    case TNone_ED72E1: return None_ED72E1__eq((None_ED72E1) t1, (None_ED72E1) t2);
    case TNone_39BC5F: return None_39BC5F__eq((None_39BC5F) t1, (None_39BC5F) t2);
    case TSome_CFA8D1: return Some_CFA8D1__eq((Some_CFA8D1) t1, (Some_CFA8D1) t2);
    case TSome_3A7E15: return Some_3A7E15__eq((Some_3A7E15) t1, (Some_3A7E15) t2);
    case TSome_0FF3DD: return Some_0FF3DD__eq((Some_0FF3DD) t1, (Some_0FF3DD) t2);
    case TSome_FCFE69: return Some_FCFE69__eq((Some_FCFE69) t1, (Some_FCFE69) t2);
    case TSome_DAEBD0: return Some_DAEBD0__eq((Some_DAEBD0) t1, (Some_DAEBD0) t2);
    case TSome_B4F3A8: return Some_B4F3A8__eq((Some_B4F3A8) t1, (Some_B4F3A8) t2);
    case TSome_9E368A: return Some_9E368A__eq((Some_9E368A) t1, (Some_9E368A) t2);
    case TSome_DDE9FD: return Some_DDE9FD__eq((Some_DDE9FD) t1, (Some_DDE9FD) t2);
    case TSome_8D03B1: return Some_8D03B1__eq((Some_8D03B1) t1, (Some_8D03B1) t2);
    case TSome_488F47: return Some_488F47__eq((Some_488F47) t1, (Some_488F47) t2);
    case TSome_482E57: return Some_482E57__eq((Some_482E57) t1, (Some_482E57) t2);
    case TSome_D29615: return Some_D29615__eq((Some_D29615) t1, (Some_D29615) t2);
    case TSome_4782C6: return Some_4782C6__eq((Some_4782C6) t1, (Some_4782C6) t2);
    case TSome_3E197E: return Some_3E197E__eq((Some_3E197E) t1, (Some_3E197E) t2);
    case TString: return String__eq((String) t1, (String) t2);
    case Tart_ArchitectureDescription: return art_ArchitectureDescription__eq((art_ArchitectureDescription) t1, (art_ArchitectureDescription) t2);
    case Tart_Bridge_Ports: return art_Bridge_Ports__eq((art_Bridge_Ports) t1, (art_Bridge_Ports) t2);
    case Tart_Connection: return art_Connection__eq((art_Connection) t1, (art_Connection) t2);
    case Tart_DispatchPropertyProtocol_Periodic: return art_DispatchPropertyProtocol_Periodic__eq((art_DispatchPropertyProtocol_Periodic) t1, (art_DispatchPropertyProtocol_Periodic) t2);
    case Tart_DispatchPropertyProtocol_Sporadic: return art_DispatchPropertyProtocol_Sporadic__eq((art_DispatchPropertyProtocol_Sporadic) t1, (art_DispatchPropertyProtocol_Sporadic) t2);
    case Tart_Empty: return art_Empty__eq((art_Empty) t1, (art_Empty) t2);
    case Tart_EventTriggered: return art_EventTriggered__eq((art_EventTriggered) t1, (art_EventTriggered) t2);
    case Tart_Port_45E54D: return art_Port_45E54D__eq((art_Port_45E54D) t1, (art_Port_45E54D) t2);
    case Tart_Port_9CBF18: return art_Port_9CBF18__eq((art_Port_9CBF18) t1, (art_Port_9CBF18) t2);
    case Tart_TimeTriggered: return art_TimeTriggered__eq((art_TimeTriggered) t1, (art_TimeTriggered) t2);
    case Tops_ISZOps_A6D40E: return ops_ISZOps_A6D40E__eq((ops_ISZOps_A6D40E) t1, (ops_ISZOps_A6D40E) t2);
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
}

void Type_cprint(void *this, B isOut) {
  #ifndef SIREUM_NO_PRINT
  TYPE type = ((Type) this)->type;
  switch (type) {
    case TTuple2_EC3B57: Tuple2_EC3B57_cprint((Tuple2_EC3B57) this, isOut); return;
    case THAMR_Simple_V4_Base_Types_Bits_Payload: HAMR_Simple_V4_Base_Types_Bits_Payload_cprint((HAMR_Simple_V4_Base_Types_Bits_Payload) this, isOut); return;
    case THAMR_Simple_V4_SW_AttestationTester_Impl_Initialization_Api: HAMR_Simple_V4_SW_AttestationTester_Impl_Initialization_Api_cprint((HAMR_Simple_V4_SW_AttestationTester_Impl_Initialization_Api) this, isOut); return;
    case THAMR_Simple_V4_SW_AttestationTester_Impl_Operational_Api: HAMR_Simple_V4_SW_AttestationTester_Impl_Operational_Api_cprint((HAMR_Simple_V4_SW_AttestationTester_Impl_Operational_Api) this, isOut); return;
    case THAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge: HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge_cprint((HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge) this, isOut); return;
    case THAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge_EntryPoints: HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge_EntryPoints_cprint((HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge_EntryPoints) this, isOut); return;
    case THAMR_Simple_V4_SW_FlightController_Impl_Initialization_Api: HAMR_Simple_V4_SW_FlightController_Impl_Initialization_Api_cprint((HAMR_Simple_V4_SW_FlightController_Impl_Initialization_Api) this, isOut); return;
    case THAMR_Simple_V4_SW_FlightController_Impl_Operational_Api: HAMR_Simple_V4_SW_FlightController_Impl_Operational_Api_cprint((HAMR_Simple_V4_SW_FlightController_Impl_Operational_Api) this, isOut); return;
    case THAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge: HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge_cprint((HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge) this, isOut); return;
    case THAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge_EntryPoints: HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge_EntryPoints_cprint((HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge_EntryPoints) this, isOut); return;
    case THAMR_Simple_V4_SW_FlightPlanner_Impl_Initialization_Api: HAMR_Simple_V4_SW_FlightPlanner_Impl_Initialization_Api_cprint((HAMR_Simple_V4_SW_FlightPlanner_Impl_Initialization_Api) this, isOut); return;
    case THAMR_Simple_V4_SW_FlightPlanner_Impl_Operational_Api: HAMR_Simple_V4_SW_FlightPlanner_Impl_Operational_Api_cprint((HAMR_Simple_V4_SW_FlightPlanner_Impl_Operational_Api) this, isOut); return;
    case THAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge: HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge_cprint((HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge) this, isOut); return;
    case THAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge_EntryPoints: HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge_EntryPoints_cprint((HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge_EntryPoints) this, isOut); return;
    case THAMR_Simple_V4_SW_RadioDriver_Impl_Initialization_Api: HAMR_Simple_V4_SW_RadioDriver_Impl_Initialization_Api_cprint((HAMR_Simple_V4_SW_RadioDriver_Impl_Initialization_Api) this, isOut); return;
    case THAMR_Simple_V4_SW_RadioDriver_Impl_Operational_Api: HAMR_Simple_V4_SW_RadioDriver_Impl_Operational_Api_cprint((HAMR_Simple_V4_SW_RadioDriver_Impl_Operational_Api) this, isOut); return;
    case THAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge: HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge_cprint((HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge) this, isOut); return;
    case THAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge_EntryPoints: HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge_EntryPoints_cprint((HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge_EntryPoints) this, isOut); return;
    case TIS_AA0F82: IS_AA0F82_cprint((IS_AA0F82) this, isOut); return;
    case TIS_C4F575: IS_C4F575_cprint((IS_C4F575) this, isOut); return;
    case TIS_948B60: IS_948B60_cprint((IS_948B60) this, isOut); return;
    case TIS_82ABD8: IS_82ABD8_cprint((IS_82ABD8) this, isOut); return;
    case TIS_7E8796: IS_7E8796_cprint((IS_7E8796) this, isOut); return;
    case TIS_08117A: IS_08117A_cprint((IS_08117A) this, isOut); return;
    case TIS_820232: IS_820232_cprint((IS_820232) this, isOut); return;
    case TMBox2_1029D1: MBox2_1029D1_cprint((MBox2_1029D1) this, isOut); return;
    case TMBox2_1CBFC4: MBox2_1CBFC4_cprint((MBox2_1CBFC4) this, isOut); return;
    case TMS_B5E3E6: MS_B5E3E6_cprint((MS_B5E3E6) this, isOut); return;
    case TMS_E444B2: MS_E444B2_cprint((MS_E444B2) this, isOut); return;
    case TMS_83D5EB: MS_83D5EB_cprint((MS_83D5EB) this, isOut); return;
    case TMS_2590FE: MS_2590FE_cprint((MS_2590FE) this, isOut); return;
    case TMS_F55A18: MS_F55A18_cprint((MS_F55A18) this, isOut); return;
    case TMS_30A5B4: MS_30A5B4_cprint((MS_30A5B4) this, isOut); return;
    case TNone_600AAD: None_600AAD_cprint((None_600AAD) this, isOut); return;
    case TNone_6557E1: None_6557E1_cprint((None_6557E1) this, isOut); return;
    case TNone_4E54E3: None_4E54E3_cprint((None_4E54E3) this, isOut); return;
    case TNone_2849BF: None_2849BF_cprint((None_2849BF) this, isOut); return;
    case TNone_43D596: None_43D596_cprint((None_43D596) this, isOut); return;
    case TNone_E951B6: None_E951B6_cprint((None_E951B6) this, isOut); return;
    case TNone_3F37D3: None_3F37D3_cprint((None_3F37D3) this, isOut); return;
    case TNone_C64652: None_C64652_cprint((None_C64652) this, isOut); return;
    case TNone_3026C5: None_3026C5_cprint((None_3026C5) this, isOut); return;
    case TNone_5C1355: None_5C1355_cprint((None_5C1355) this, isOut); return;
    case TNone_76463B: None_76463B_cprint((None_76463B) this, isOut); return;
    case TNone_734370: None_734370_cprint((None_734370) this, isOut); return;
    case TNone_964667: None_964667_cprint((None_964667) this, isOut); return;
    case TNone_ED72E1: None_ED72E1_cprint((None_ED72E1) this, isOut); return;
    case TNone_39BC5F: None_39BC5F_cprint((None_39BC5F) this, isOut); return;
    case TSome_CFA8D1: Some_CFA8D1_cprint((Some_CFA8D1) this, isOut); return;
    case TSome_3A7E15: Some_3A7E15_cprint((Some_3A7E15) this, isOut); return;
    case TSome_0FF3DD: Some_0FF3DD_cprint((Some_0FF3DD) this, isOut); return;
    case TSome_FCFE69: Some_FCFE69_cprint((Some_FCFE69) this, isOut); return;
    case TSome_DAEBD0: Some_DAEBD0_cprint((Some_DAEBD0) this, isOut); return;
    case TSome_B4F3A8: Some_B4F3A8_cprint((Some_B4F3A8) this, isOut); return;
    case TSome_9E368A: Some_9E368A_cprint((Some_9E368A) this, isOut); return;
    case TSome_DDE9FD: Some_DDE9FD_cprint((Some_DDE9FD) this, isOut); return;
    case TSome_8D03B1: Some_8D03B1_cprint((Some_8D03B1) this, isOut); return;
    case TSome_488F47: Some_488F47_cprint((Some_488F47) this, isOut); return;
    case TSome_482E57: Some_482E57_cprint((Some_482E57) this, isOut); return;
    case TSome_D29615: Some_D29615_cprint((Some_D29615) this, isOut); return;
    case TSome_4782C6: Some_4782C6_cprint((Some_4782C6) this, isOut); return;
    case TSome_3E197E: Some_3E197E_cprint((Some_3E197E) this, isOut); return;
    case TString: String_cprint((String) this, isOut); return;
    case Tart_ArchitectureDescription: art_ArchitectureDescription_cprint((art_ArchitectureDescription) this, isOut); return;
    case Tart_Bridge_Ports: art_Bridge_Ports_cprint((art_Bridge_Ports) this, isOut); return;
    case Tart_Connection: art_Connection_cprint((art_Connection) this, isOut); return;
    case Tart_DispatchPropertyProtocol_Periodic: art_DispatchPropertyProtocol_Periodic_cprint((art_DispatchPropertyProtocol_Periodic) this, isOut); return;
    case Tart_DispatchPropertyProtocol_Sporadic: art_DispatchPropertyProtocol_Sporadic_cprint((art_DispatchPropertyProtocol_Sporadic) this, isOut); return;
    case Tart_Empty: art_Empty_cprint((art_Empty) this, isOut); return;
    case Tart_EventTriggered: art_EventTriggered_cprint((art_EventTriggered) this, isOut); return;
    case Tart_Port_45E54D: art_Port_45E54D_cprint((art_Port_45E54D) this, isOut); return;
    case Tart_Port_9CBF18: art_Port_9CBF18_cprint((art_Port_9CBF18) this, isOut); return;
    case Tart_TimeTriggered: art_TimeTriggered_cprint((art_TimeTriggered) this, isOut); return;
    case Tops_ISZOps_A6D40E: ops_ISZOps_A6D40E_cprint((ops_ISZOps_A6D40E) this, isOut); return;
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
  #endif
}

void Type_string_(STACK_FRAME String result, void *this) {
  TYPE type = ((Type) this)->type;
  switch (type) {
    case TTuple2_EC3B57: Tuple2_EC3B57_string_(CALLER result, (Tuple2_EC3B57) this); return;
    case THAMR_Simple_V4_Base_Types_Bits_Payload: HAMR_Simple_V4_Base_Types_Bits_Payload_string_(CALLER result, (HAMR_Simple_V4_Base_Types_Bits_Payload) this); return;
    case THAMR_Simple_V4_SW_AttestationTester_Impl_Initialization_Api: HAMR_Simple_V4_SW_AttestationTester_Impl_Initialization_Api_string_(CALLER result, (HAMR_Simple_V4_SW_AttestationTester_Impl_Initialization_Api) this); return;
    case THAMR_Simple_V4_SW_AttestationTester_Impl_Operational_Api: HAMR_Simple_V4_SW_AttestationTester_Impl_Operational_Api_string_(CALLER result, (HAMR_Simple_V4_SW_AttestationTester_Impl_Operational_Api) this); return;
    case THAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge: HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge_string_(CALLER result, (HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge) this); return;
    case THAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge_EntryPoints: HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge_EntryPoints_string_(CALLER result, (HAMR_Simple_V4_SW_AttestationTester_Impl_SW_AttestationTester_Bridge_EntryPoints) this); return;
    case THAMR_Simple_V4_SW_FlightController_Impl_Initialization_Api: HAMR_Simple_V4_SW_FlightController_Impl_Initialization_Api_string_(CALLER result, (HAMR_Simple_V4_SW_FlightController_Impl_Initialization_Api) this); return;
    case THAMR_Simple_V4_SW_FlightController_Impl_Operational_Api: HAMR_Simple_V4_SW_FlightController_Impl_Operational_Api_string_(CALLER result, (HAMR_Simple_V4_SW_FlightController_Impl_Operational_Api) this); return;
    case THAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge: HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge_string_(CALLER result, (HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge) this); return;
    case THAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge_EntryPoints: HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge_EntryPoints_string_(CALLER result, (HAMR_Simple_V4_SW_FlightController_Impl_SW_FlightController_Bridge_EntryPoints) this); return;
    case THAMR_Simple_V4_SW_FlightPlanner_Impl_Initialization_Api: HAMR_Simple_V4_SW_FlightPlanner_Impl_Initialization_Api_string_(CALLER result, (HAMR_Simple_V4_SW_FlightPlanner_Impl_Initialization_Api) this); return;
    case THAMR_Simple_V4_SW_FlightPlanner_Impl_Operational_Api: HAMR_Simple_V4_SW_FlightPlanner_Impl_Operational_Api_string_(CALLER result, (HAMR_Simple_V4_SW_FlightPlanner_Impl_Operational_Api) this); return;
    case THAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge: HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge_string_(CALLER result, (HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge) this); return;
    case THAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge_EntryPoints: HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge_EntryPoints_string_(CALLER result, (HAMR_Simple_V4_SW_FlightPlanner_Impl_SW_FlightPlanner_Bridge_EntryPoints) this); return;
    case THAMR_Simple_V4_SW_RadioDriver_Impl_Initialization_Api: HAMR_Simple_V4_SW_RadioDriver_Impl_Initialization_Api_string_(CALLER result, (HAMR_Simple_V4_SW_RadioDriver_Impl_Initialization_Api) this); return;
    case THAMR_Simple_V4_SW_RadioDriver_Impl_Operational_Api: HAMR_Simple_V4_SW_RadioDriver_Impl_Operational_Api_string_(CALLER result, (HAMR_Simple_V4_SW_RadioDriver_Impl_Operational_Api) this); return;
    case THAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge: HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge_string_(CALLER result, (HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge) this); return;
    case THAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge_EntryPoints: HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge_EntryPoints_string_(CALLER result, (HAMR_Simple_V4_SW_RadioDriver_Impl_SW_Radio_Bridge_EntryPoints) this); return;
    case TIS_AA0F82: IS_AA0F82_string_(CALLER result, (IS_AA0F82) this); return;
    case TIS_C4F575: IS_C4F575_string_(CALLER result, (IS_C4F575) this); return;
    case TIS_948B60: IS_948B60_string_(CALLER result, (IS_948B60) this); return;
    case TIS_82ABD8: IS_82ABD8_string_(CALLER result, (IS_82ABD8) this); return;
    case TIS_7E8796: IS_7E8796_string_(CALLER result, (IS_7E8796) this); return;
    case TIS_08117A: IS_08117A_string_(CALLER result, (IS_08117A) this); return;
    case TIS_820232: IS_820232_string_(CALLER result, (IS_820232) this); return;
    case TMBox2_1029D1: MBox2_1029D1_string_(CALLER result, (MBox2_1029D1) this); return;
    case TMBox2_1CBFC4: MBox2_1CBFC4_string_(CALLER result, (MBox2_1CBFC4) this); return;
    case TMS_B5E3E6: MS_B5E3E6_string_(CALLER result, (MS_B5E3E6) this); return;
    case TMS_E444B2: MS_E444B2_string_(CALLER result, (MS_E444B2) this); return;
    case TMS_83D5EB: MS_83D5EB_string_(CALLER result, (MS_83D5EB) this); return;
    case TMS_2590FE: MS_2590FE_string_(CALLER result, (MS_2590FE) this); return;
    case TMS_F55A18: MS_F55A18_string_(CALLER result, (MS_F55A18) this); return;
    case TMS_30A5B4: MS_30A5B4_string_(CALLER result, (MS_30A5B4) this); return;
    case TNone_600AAD: None_600AAD_string_(CALLER result, (None_600AAD) this); return;
    case TNone_6557E1: None_6557E1_string_(CALLER result, (None_6557E1) this); return;
    case TNone_4E54E3: None_4E54E3_string_(CALLER result, (None_4E54E3) this); return;
    case TNone_2849BF: None_2849BF_string_(CALLER result, (None_2849BF) this); return;
    case TNone_43D596: None_43D596_string_(CALLER result, (None_43D596) this); return;
    case TNone_E951B6: None_E951B6_string_(CALLER result, (None_E951B6) this); return;
    case TNone_3F37D3: None_3F37D3_string_(CALLER result, (None_3F37D3) this); return;
    case TNone_C64652: None_C64652_string_(CALLER result, (None_C64652) this); return;
    case TNone_3026C5: None_3026C5_string_(CALLER result, (None_3026C5) this); return;
    case TNone_5C1355: None_5C1355_string_(CALLER result, (None_5C1355) this); return;
    case TNone_76463B: None_76463B_string_(CALLER result, (None_76463B) this); return;
    case TNone_734370: None_734370_string_(CALLER result, (None_734370) this); return;
    case TNone_964667: None_964667_string_(CALLER result, (None_964667) this); return;
    case TNone_ED72E1: None_ED72E1_string_(CALLER result, (None_ED72E1) this); return;
    case TNone_39BC5F: None_39BC5F_string_(CALLER result, (None_39BC5F) this); return;
    case TSome_CFA8D1: Some_CFA8D1_string_(CALLER result, (Some_CFA8D1) this); return;
    case TSome_3A7E15: Some_3A7E15_string_(CALLER result, (Some_3A7E15) this); return;
    case TSome_0FF3DD: Some_0FF3DD_string_(CALLER result, (Some_0FF3DD) this); return;
    case TSome_FCFE69: Some_FCFE69_string_(CALLER result, (Some_FCFE69) this); return;
    case TSome_DAEBD0: Some_DAEBD0_string_(CALLER result, (Some_DAEBD0) this); return;
    case TSome_B4F3A8: Some_B4F3A8_string_(CALLER result, (Some_B4F3A8) this); return;
    case TSome_9E368A: Some_9E368A_string_(CALLER result, (Some_9E368A) this); return;
    case TSome_DDE9FD: Some_DDE9FD_string_(CALLER result, (Some_DDE9FD) this); return;
    case TSome_8D03B1: Some_8D03B1_string_(CALLER result, (Some_8D03B1) this); return;
    case TSome_488F47: Some_488F47_string_(CALLER result, (Some_488F47) this); return;
    case TSome_482E57: Some_482E57_string_(CALLER result, (Some_482E57) this); return;
    case TSome_D29615: Some_D29615_string_(CALLER result, (Some_D29615) this); return;
    case TSome_4782C6: Some_4782C6_string_(CALLER result, (Some_4782C6) this); return;
    case TSome_3E197E: Some_3E197E_string_(CALLER result, (Some_3E197E) this); return;
    case TString: String_string_(CALLER result, (String) this); return;
    case Tart_ArchitectureDescription: art_ArchitectureDescription_string_(CALLER result, (art_ArchitectureDescription) this); return;
    case Tart_Bridge_Ports: art_Bridge_Ports_string_(CALLER result, (art_Bridge_Ports) this); return;
    case Tart_Connection: art_Connection_string_(CALLER result, (art_Connection) this); return;
    case Tart_DispatchPropertyProtocol_Periodic: art_DispatchPropertyProtocol_Periodic_string_(CALLER result, (art_DispatchPropertyProtocol_Periodic) this); return;
    case Tart_DispatchPropertyProtocol_Sporadic: art_DispatchPropertyProtocol_Sporadic_string_(CALLER result, (art_DispatchPropertyProtocol_Sporadic) this); return;
    case Tart_Empty: art_Empty_string_(CALLER result, (art_Empty) this); return;
    case Tart_EventTriggered: art_EventTriggered_string_(CALLER result, (art_EventTriggered) this); return;
    case Tart_Port_45E54D: art_Port_45E54D_string_(CALLER result, (art_Port_45E54D) this); return;
    case Tart_Port_9CBF18: art_Port_9CBF18_string_(CALLER result, (art_Port_9CBF18) this); return;
    case Tart_TimeTriggered: art_TimeTriggered_string_(CALLER result, (art_TimeTriggered) this); return;
    case Tops_ISZOps_A6D40E: ops_ISZOps_A6D40E_string_(CALLER result, (ops_ISZOps_A6D40E) this); return;
    default: fprintf(stderr, "%s: %d\n", "Unexpected TYPE: ", type); exit(1);
  }
}

void Z_apply(Option_882048 result, String s) {
  char *endptr;
  errno = 0;
  long long n = strtoll(s->value, &endptr, 0);
  if (errno) {
    errno = 0;
    Type_assign(result, &((struct None_76463B) { .type = TNone_76463B }), sizeof(struct None_76463B));
    return;
  }
  if (&s->value[s->size] - endptr == 0 && INT64_MIN <= n && n <= INT64_MAX)
    Type_assign(result, &((struct Some_488F47) { .type = TSome_488F47, .value = (Z) n }), sizeof(struct Some_488F47));
  else Type_assign(result, &((struct None_76463B) { .type = TNone_76463B }), sizeof(struct None_76463B));
}