#ifndef ATTESTATIONTESTER_IMPL_SW_ATTESTATIONTESTER_ATTESTATIONTESTER_H
#define ATTESTATIONTESTER_IMPL_SW_ATTESTATIONTESTER_ATTESTATIONTESTER_H

#include <all.h>

Unit HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_initialise_(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_finalise_(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_timeTriggered_(STACK_FRAME_ONLY);

#endif
