#include <CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter.h>

Unit CASE_MONITOR2_TEST_VPM_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter.c", "", "CASE_MONITOR2_TEST_VPM_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter_initialiseArchitecture", 0);

  CASE_MONITOR2_TEST_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_CASE_Monitor2_initialiseArchitecture(SF_LAST);
}

Unit CASE_MONITOR2_TEST_VPM_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter.c", "", "CASE_MONITOR2_TEST_VPM_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter_initialiseEntryPoint", 0);

  CASE_MONITOR2_TEST_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_CASE_Monitor2_initialiseEntryPoint(SF_LAST);
}

Unit CASE_MONITOR2_TEST_VPM_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter.c", "", "CASE_MONITOR2_TEST_VPM_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter_computeEntryPoint", 0);

  CASE_MONITOR2_TEST_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_CASE_Monitor2_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints CASE_MONITOR2_TEST_VPM_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter.c", "", "CASE_MONITOR2_TEST_VPM_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter_entryPoints", 0);

  return CASE_MONITOR2_TEST_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_CASE_Monitor2_entryPoints(SF_LAST);
}
