#ifndef CASE_MONITOR2_IMPL_CASE_MONITOR2_CASE_MONITOR2_ADAPTER_H
#define CASE_MONITOR2_IMPL_CASE_MONITOR2_CASE_MONITOR2_ADAPTER_H

#include <all.h>

Unit CASE_MONITOR2_TEST_VPM_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit CASE_MONITOR2_TEST_VPM_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit CASE_MONITOR2_TEST_VPM_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints CASE_MONITOR2_TEST_VPM_CASE_Monitor2_Impl_CASE_Monitor2_CASE_Monitor2_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
