#ifndef CONSUMER_THREAD_I_CONSUMER_CONSUMER_H
#define CONSUMER_THREAD_I_CONSUMER_CONSUMER_H

#include <all.h>

Unit base_test_data_port_periodic_domains_consumer_thread_i_consumer_consumer_initialise_(STACK_FRAME_ONLY);

Unit base_test_data_port_periodic_domains_consumer_thread_i_consumer_consumer_finalise_(STACK_FRAME_ONLY);

Unit base_test_data_port_periodic_domains_consumer_thread_i_consumer_consumer_timeTriggered_(STACK_FRAME_ONLY);

#endif
