#ifndef PRODUCER_T_I_PRODUCER_PRODUCER_H
#define PRODUCER_T_I_PRODUCER_PRODUCER_H

#include <all.h>

Unit base_test_event_data_port_periodic_domains_producer_t_i_producer_producer_initialise_(STACK_FRAME_ONLY);

Unit base_test_event_data_port_periodic_domains_producer_t_i_producer_producer_finalise_(STACK_FRAME_ONLY);

Unit base_test_event_data_port_periodic_domains_producer_t_i_producer_producer_timeTriggered_(STACK_FRAME_ONLY);

#endif
