#ifndef ATTESTATIONGATE_IMPL_SW_ATTESTATIONGATE_ATTESTATIONGATE_ADAPTER_H
#define ATTESTATIONGATE_IMPL_SW_ATTESTATIONGATE_ATTESTATIONGATE_ADAPTER_H

#include <all.h>

Unit HAMR_SW_AttestationGate_Impl_SW_AttestationGate_AttestationGate_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationGate_Impl_SW_AttestationGate_AttestationGate_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationGate_Impl_SW_AttestationGate_AttestationGate_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints HAMR_SW_AttestationGate_Impl_SW_AttestationGate_AttestationGate_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
