#ifndef ATTESTATIONTESTER_IMPL_ATTESTATIONTESTER_ATTESTATIONTESTER_H
#define ATTESTATIONTESTER_IMPL_ATTESTATIONTESTER_ATTESTATIONTESTER_H

#include <all.h>

Unit HAMR_SW_AttestationTester_Impl_AttestationTester_AttestationTester_initialise_(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationTester_Impl_AttestationTester_AttestationTester_finalise_(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationTester_Impl_AttestationTester_AttestationTester_handle_AttestationRequest_(
  STACK_FRAME
  HAMR_SW_AttestationRequestMsg_Impl value);

#endif
