#ifndef CASE_MONITOR_REQ_THR_IMPL_MCMP_PROC_SW_MON_REQ_CASE_MONITOR_REQ_H
#define CASE_MONITOR_REQ_THR_IMPL_MCMP_PROC_SW_MON_REQ_CASE_MONITOR_REQ_H

#include <all.h>

Unit hamr_SW_CASE_Monitor_Req_thr_Impl_MCMP_PROC_SW_MON_REQ_CASE_Monitor_Req_initialise_(STACK_FRAME_ONLY);

Unit hamr_SW_CASE_Monitor_Req_thr_Impl_MCMP_PROC_SW_MON_REQ_CASE_Monitor_Req_finalise_(STACK_FRAME_ONLY);

Unit hamr_SW_CASE_Monitor_Req_thr_Impl_MCMP_PROC_SW_MON_REQ_CASE_Monitor_Req_timeTriggered_(STACK_FRAME_ONLY);

#endif
