#ifndef FLYZONESDATABASE_THR_IMPL_MCMP_PROC_SW_FLYZONES_FLYZONESDATABASE_ADAPTER_H
#define FLYZONESDATABASE_THR_IMPL_MCMP_PROC_SW_FLYZONES_FLYZONESDATABASE_ADAPTER_H

#include <all.h>

Unit hamr_SW_FlyZonesDatabase_thr_Impl_MCMP_PROC_SW_FlyZones_FlyZonesDatabase_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit hamr_SW_FlyZonesDatabase_thr_Impl_MCMP_PROC_SW_FlyZones_FlyZonesDatabase_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit hamr_SW_FlyZonesDatabase_thr_Impl_MCMP_PROC_SW_FlyZones_FlyZonesDatabase_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints hamr_SW_FlyZonesDatabase_thr_Impl_MCMP_PROC_SW_FlyZones_FlyZonesDatabase_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
