#ifndef ATTESTATIONGATE_IMPL_SW_ATTESTATIONGATE_ATTESTATIONGATE_H
#define ATTESTATIONGATE_IMPL_SW_ATTESTATIONGATE_ATTESTATIONGATE_H

#include <all.h>

Unit HAMR_SW_AttestationGate_Impl_SW_AttestationGate_AttestationGate_initialise_(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationGate_Impl_SW_AttestationGate_AttestationGate_finalise_(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationGate_Impl_SW_AttestationGate_AttestationGate_timeTriggered_(STACK_FRAME_ONLY);

#endif
