#ifndef ATTESTATIONGATE_IMPL_ATTESTATIONGATE_ATTESTATIONGATE_H
#define ATTESTATIONGATE_IMPL_ATTESTATIONGATE_ATTESTATIONGATE_H

#include <all.h>

Unit HAMR_SW_AttestationGate_Impl_AttestationGate_AttestationGate_initialise_(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationGate_Impl_AttestationGate_AttestationGate_finalise_(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationGate_Impl_AttestationGate_AttestationGate_handle_MissionCommand_in_(
  STACK_FRAME
  HAMR_SW_RF_Msg_Impl value);

Unit HAMR_SW_AttestationGate_Impl_AttestationGate_AttestationGate_handle_TrustedIds_(
  STACK_FRAME
  HAMR_SW_AllowList_Impl value);

#endif
