#ifndef FLIGHTCONTROLLER_IMPL_SW_FLIGHTCONTROLLER_FLIGHTCONTROLLER_ADAPTER_H
#define FLIGHTCONTROLLER_IMPL_SW_FLIGHTCONTROLLER_FLIGHTCONTROLLER_ADAPTER_H

#include <all.h>

Unit HAMR_SW_FlightController_Impl_SW_FlightController_FlightController_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit HAMR_SW_FlightController_Impl_SW_FlightController_FlightController_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit HAMR_SW_FlightController_Impl_SW_FlightController_FlightController_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints HAMR_SW_FlightController_Impl_SW_FlightController_FlightController_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
