#ifndef MONITOR_IMPL_SW_MONITOR_MONITOR_ADAPTER_H
#define MONITOR_IMPL_SW_MONITOR_MONITOR_ADAPTER_H

#include <all.h>

Unit HAMR_SW_Monitor_Impl_SW_Monitor_Monitor_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit HAMR_SW_Monitor_Impl_SW_Monitor_Monitor_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit HAMR_SW_Monitor_Impl_SW_Monitor_Monitor_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints HAMR_SW_Monitor_Impl_SW_Monitor_Monitor_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
