#ifndef ATTESTATIONMANAGER_IMPL_SW_ATTESTATIONMANAGER_ATTESTATIONMANAGER_ADAPTER_H
#define ATTESTATIONMANAGER_IMPL_SW_ATTESTATIONMANAGER_ATTESTATIONMANAGER_ADAPTER_H

#include <all.h>

Unit HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints HAMR_SW_AttestationManager_Impl_SW_AttestationManager_AttestationManager_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
