#ifndef OUTPUT_IMPL_OUTPUT_OUTPUT_ADAPTER_H
#define OUTPUT_IMPL_OUTPUT_OUTPUT_ADAPTER_H

#include <all.h>

Unit CASE_MONITOR_2_TEST_VPM_TEST_Output_impl_Output_Output_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit CASE_MONITOR_2_TEST_VPM_TEST_Output_impl_Output_Output_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit CASE_MONITOR_2_TEST_VPM_TEST_Output_impl_Output_Output_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints CASE_MONITOR_2_TEST_VPM_TEST_Output_impl_Output_Output_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
