#ifndef CASE_MONITOR_REQ_THR_IMPL_MCMP_PROC_SW_MON_REQ_CASE_MONITOR_REQ_ADAPTER_H
#define CASE_MONITOR_REQ_THR_IMPL_MCMP_PROC_SW_MON_REQ_CASE_MONITOR_REQ_ADAPTER_H

#include <all.h>

Unit hamr_SW_CASE_Monitor_Req_thr_Impl_MCMP_PROC_SW_MON_REQ_CASE_Monitor_Req_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit hamr_SW_CASE_Monitor_Req_thr_Impl_MCMP_PROC_SW_MON_REQ_CASE_Monitor_Req_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit hamr_SW_CASE_Monitor_Req_thr_Impl_MCMP_PROC_SW_MON_REQ_CASE_Monitor_Req_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints hamr_SW_CASE_Monitor_Req_thr_Impl_MCMP_PROC_SW_MON_REQ_CASE_Monitor_Req_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
