#include <ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter.h>

Unit HAMR_SW_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter.c", "", "HAMR_SW_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter_initialiseArchitecture", 0);

  HAMR_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_ResponseMonitor_initialiseArchitecture(SF_LAST);
}

Unit HAMR_SW_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter.c", "", "HAMR_SW_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter_initialiseEntryPoint", 0);

  HAMR_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_ResponseMonitor_initialiseEntryPoint(SF_LAST);
}

Unit HAMR_SW_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter.c", "", "HAMR_SW_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter_computeEntryPoint", 0);

  HAMR_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_ResponseMonitor_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints HAMR_SW_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter.c", "", "HAMR_SW_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter_entryPoints", 0);

  return HAMR_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_ResponseMonitor_entryPoints(SF_LAST);
}
