#ifndef RESPONSEMONITOR_IMPL_SW_RESPONSEMONITOR_RESPONSEMONITOR_ADAPTER_H
#define RESPONSEMONITOR_IMPL_SW_RESPONSEMONITOR_RESPONSEMONITOR_ADAPTER_H

#include <all.h>

Unit HAMR_SW_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit HAMR_SW_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit HAMR_SW_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints HAMR_SW_ResponseMonitor_Impl_SW_ResponseMonitor_ResponseMonitor_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
