#include <CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter.h>

Unit attestation_gate_CASE_AttestationGate_CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter.c", "", "attestation_gate_CASE_AttestationGate_CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter_initialiseArchitecture", 0);

  attestation_gate_CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_CASE_AttestationGate_initialiseArchitecture(SF_LAST);
}

Unit attestation_gate_CASE_AttestationGate_CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter.c", "", "attestation_gate_CASE_AttestationGate_CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter_initialiseEntryPoint", 0);

  attestation_gate_CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_CASE_AttestationGate_initialiseEntryPoint(SF_LAST);
}

Unit attestation_gate_CASE_AttestationGate_CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter.c", "", "attestation_gate_CASE_AttestationGate_CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter_computeEntryPoint", 0);

  attestation_gate_CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_CASE_AttestationGate_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints attestation_gate_CASE_AttestationGate_CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter.c", "", "attestation_gate_CASE_AttestationGate_CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_adapter_entryPoints", 0);

  return attestation_gate_CASE_AttestationGate_thr_Impl_am_gate_CASE_AttestationGate_CASE_AttestationGate_entryPoints(SF_LAST);
}
