#ifndef ATTESTATIONMANAGER_IMPL_ATTESTATIONMANAGER_ATTESTATIONMANAGER_H
#define ATTESTATIONMANAGER_IMPL_ATTESTATIONMANAGER_ATTESTATIONMANAGER_H

#include <all.h>

Unit HAMR_SW_AttestationManager_Impl_AttestationManager_AttestationManager_initialise_(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationManager_Impl_AttestationManager_AttestationManager_finalise_(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationManager_Impl_AttestationManager_AttestationManager_handle_AttestationResponse_(
  STACK_FRAME
  HAMR_SW_AttestationResponseMsg_Impl value);

#endif
