#ifndef CASE_ATTESTATIONGATE_THR_IMPL_MCMP_PROC_SW_AM_GATE_CASE_ATTESTATIONGATE_ADAPTER_H
#define CASE_ATTESTATIONGATE_THR_IMPL_MCMP_PROC_SW_AM_GATE_CASE_ATTESTATIONGATE_ADAPTER_H

#include <all.h>

Unit hamr_SW_CASE_AttestationGate_thr_Impl_MCMP_PROC_SW_AM_Gate_CASE_AttestationGate_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit hamr_SW_CASE_AttestationGate_thr_Impl_MCMP_PROC_SW_AM_Gate_CASE_AttestationGate_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit hamr_SW_CASE_AttestationGate_thr_Impl_MCMP_PROC_SW_AM_Gate_CASE_AttestationGate_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints hamr_SW_CASE_AttestationGate_thr_Impl_MCMP_PROC_SW_AM_Gate_CASE_AttestationGate_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
