#ifndef RADIODRIVER_ATTESTATION_IMPL_RADIO_RADIODRIVER_ATTESTATION_H
#define RADIODRIVER_ATTESTATION_IMPL_RADIO_RADIODRIVER_ATTESTATION_H

#include <all.h>

Unit HAMR_SW_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_initialise_(STACK_FRAME_ONLY);

Unit HAMR_SW_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_finalise_(STACK_FRAME_ONLY);

Unit HAMR_SW_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_handle_AttestationTesterResponse_(
  STACK_FRAME
  HAMR_SW_AttestationResponseMsg_Impl value);

Unit HAMR_SW_RadioDriver_Attestation_Impl_Radio_RadioDriver_Attestation_handle_AttestationRequest_(
  STACK_FRAME
  HAMR_SW_AttestationRequestMsg_Impl value);

#endif
