#include <AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter.h>

Unit HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter.c", "", "HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter_initialiseArchitecture", 0);

  HAMR_AttestationTester_Impl_SW_AttestationTester_AttestationTester_AttestationTester_initialiseArchitecture(SF_LAST);
}

Unit HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter.c", "", "HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter_initialiseEntryPoint", 0);

  HAMR_AttestationTester_Impl_SW_AttestationTester_AttestationTester_AttestationTester_initialiseEntryPoint(SF_LAST);
}

Unit HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter.c", "", "HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter_computeEntryPoint", 0);

  HAMR_AttestationTester_Impl_SW_AttestationTester_AttestationTester_AttestationTester_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter.c", "", "HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter_entryPoints", 0);

  return HAMR_AttestationTester_Impl_SW_AttestationTester_AttestationTester_AttestationTester_entryPoints(SF_LAST);
}
