#ifndef ATTESTATIONTESTER_IMPL_SW_ATTESTATIONTESTER_ATTESTATIONTESTER_ADAPTER_H
#define ATTESTATIONTESTER_IMPL_SW_ATTESTATIONTESTER_ATTESTATIONTESTER_ADAPTER_H

#include <all.h>

Unit HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter_initialiseArchitecture(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter_initialiseEntryPoint(STACK_FRAME_ONLY);

Unit HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter_computeEntryPoint(STACK_FRAME_ONLY);

art_Bridge_EntryPoints HAMR_SW_AttestationTester_Impl_SW_AttestationTester_AttestationTester_adapter_entryPoints(STACK_FRAME_ONLY);

#endif
