#include <UxAS_thr_Impl_uxas_UxAS_thread_adapter.h>

Unit attestation_gate_SysContext_UxAS_thr_Impl_uxas_UxAS_thread_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "UxAS_thr_Impl_uxas_UxAS_thread_adapter.c", "", "attestation_gate_SysContext_UxAS_thr_Impl_uxas_UxAS_thread_adapter_initialiseArchitecture", 0);

  attestation_gate_UxAS_thr_Impl_uxas_UxAS_thread_UxAS_thread_initialiseArchitecture(SF_LAST);
}

Unit attestation_gate_SysContext_UxAS_thr_Impl_uxas_UxAS_thread_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "UxAS_thr_Impl_uxas_UxAS_thread_adapter.c", "", "attestation_gate_SysContext_UxAS_thr_Impl_uxas_UxAS_thread_adapter_initialiseEntryPoint", 0);

  attestation_gate_UxAS_thr_Impl_uxas_UxAS_thread_UxAS_thread_initialiseEntryPoint(SF_LAST);
}

Unit attestation_gate_SysContext_UxAS_thr_Impl_uxas_UxAS_thread_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "UxAS_thr_Impl_uxas_UxAS_thread_adapter.c", "", "attestation_gate_SysContext_UxAS_thr_Impl_uxas_UxAS_thread_adapter_computeEntryPoint", 0);

  attestation_gate_UxAS_thr_Impl_uxas_UxAS_thread_UxAS_thread_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints attestation_gate_SysContext_UxAS_thr_Impl_uxas_UxAS_thread_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "UxAS_thr_Impl_uxas_UxAS_thread_adapter.c", "", "attestation_gate_SysContext_UxAS_thr_Impl_uxas_UxAS_thread_adapter_entryPoints", 0);

  return attestation_gate_UxAS_thr_Impl_uxas_UxAS_thread_UxAS_thread_entryPoints(SF_LAST);
}
