#include <consumer_t_i_consumer_consumer_adapter.h>

Unit base_test_event_data_port_periodic_domains_consumer_t_i_consumer_consumer_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "consumer_t_i_consumer_consumer_adapter.c", "", "base_test_event_data_port_periodic_domains_consumer_t_i_consumer_consumer_adapter_initialiseArchitecture", 0);

  base_consumer_t_i_consumer_consumer_consumer_initialiseArchitecture(SF_LAST);
}

Unit base_test_event_data_port_periodic_domains_consumer_t_i_consumer_consumer_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "consumer_t_i_consumer_consumer_adapter.c", "", "base_test_event_data_port_periodic_domains_consumer_t_i_consumer_consumer_adapter_initialiseEntryPoint", 0);

  base_consumer_t_i_consumer_consumer_consumer_initialiseEntryPoint(SF_LAST);
}

Unit base_test_event_data_port_periodic_domains_consumer_t_i_consumer_consumer_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "consumer_t_i_consumer_consumer_adapter.c", "", "base_test_event_data_port_periodic_domains_consumer_t_i_consumer_consumer_adapter_computeEntryPoint", 0);

  base_consumer_t_i_consumer_consumer_consumer_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints base_test_event_data_port_periodic_domains_consumer_t_i_consumer_consumer_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "consumer_t_i_consumer_consumer_adapter.c", "", "base_test_event_data_port_periodic_domains_consumer_t_i_consumer_consumer_adapter_entryPoints", 0);

  return base_consumer_t_i_consumer_consumer_consumer_entryPoints(SF_LAST);
}
