#include <CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter.h>

Unit HAMR_SW_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter_initialiseArchitecture(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter.c", "", "HAMR_SW_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter_initialiseArchitecture", 0);

  HAMR_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_CASE_AttestationGate_initialiseArchitecture(SF_LAST);
}

Unit HAMR_SW_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter_initialiseEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter.c", "", "HAMR_SW_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter_initialiseEntryPoint", 0);

  HAMR_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_CASE_AttestationGate_initialiseEntryPoint(SF_LAST);
}

Unit HAMR_SW_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter_computeEntryPoint(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter.c", "", "HAMR_SW_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter_computeEntryPoint", 0);

  HAMR_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_CASE_AttestationGate_computeEntryPoint(SF_LAST);
}

art_Bridge_EntryPoints HAMR_SW_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter_entryPoints(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter.c", "", "HAMR_SW_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_adapter_entryPoints", 0);

  return HAMR_CASE_AttestationGate_Impl_SW_AttestationGate_CASE_AttestationGate_CASE_AttestationGate_entryPoints(SF_LAST);
}
